### ISSUE TITLE
Filtyper

### ISSUE THREAD

**Issue by CCTDadam** [Graunephar/CCTD_library_theme#14]
Jeg er løbet ind i at der er en masse filtyper som jeg ikke må uploade. Det gælder eksempelvis filer skrevet i C, R og Fortran. Lige nu har jeg bare smækket dem allesammen i en zip-fil, men det er imod det princip I har med at undgå mange klik for brugeren.

**Comment by Graunephar** [comment]
Fixed with everything but c. See #20
