### ISSUE TITLE
NetLogo-filer downloades ikke

### ISSUE THREAD

**Issue by CCTDadam** [Graunephar/CCTD_library_theme#17]
Når jeg klikker på word- og pdf-filer på hjemmesiden bliver de fint hentet ned. Når jeg klikker på png'er downloader den ikke, men vises fint i min browser. Men når jeg klikker på NetLogo-filer bliver følgende vist i min browser:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/51358623/59753359-3c81f900-9284-11e9-85c7-1ddd6e9825f3.png">

**Comment by Graunephar** [comment]
Fixed in apache. through .htaccess

https://css-tricks.com/snippets/htaccess/force-files-to-download-not-open-in-browser/
