### ISSUE TITLE
Skoleår

### ISSUE THREAD

**Issue by CCTDadam** [Graunephar/CCTD_library_theme#4]
Modsat de andre tag-felter bliver tekst ikke til en lille grå boks når jeg har skrevet det ind i feltet "skoleår". Teksten bliver heller ikke gemt når jeg udgiver post'en.

**Comment by CCTDadam** [comment]
Det er naturligvis fordi jeg skal skrive komma for at afslutte en tekststreng. My bad.

**Comment by Graunephar** [comment]
Komma eller trykke  "enter" mellem hvert tag

**Comment by Graunephar** [comment]
Ikke helt en duplicate men alligevel samme feature

Duplicate #9
