### ISSUE TITLE
"Karantæne"?

### ISSUE THREAD

**Issue by CCTDadam** [Graunephar/CCTD_library_theme#5]
Når jeg prøver på at lave ændringer i forløb får jeg oftest ikke lov til at opdatere posten. Er der en timer som giver en slags karantæne for at forhindre at posts ændres for ofte?

**Comment by CCTDadam** [comment]
Hmmm... Prøvede noget dumt som virkede. Jeg skal åbenbart ændre i teksten for at den vil opdatere post'en. Så jeg skriver sadfk og sletter det igen, så virker det.

**Comment by Graunephar** [comment]
Duplicate of #8 

Du har helt ret Adam. Det er en fejl jeg endnu ikke har rettet. 

Din dumme løsning er den korrekte. Det er fordi wordpres ikke ser hverken ændringer af filer eller forfatter som ændringer til forløbet. Den gemmer dem dog samtidig med at den gemmer forløbet.

**Comment by Graunephar** [comment]
Så blev den rettet
