### ISSUE TITLE
Vist filnavn

### ISSUE THREAD

**Issue by CCTDadam** [Graunephar/CCTD_library_theme#6]
Hej igen

Det er en stor fordel hvis samtlige filer jeg uploader vises som "filer.zip" hhv. "poster.pdf". Problemet er at lige nu tager hjemmesiden det navn som er i hjemmesidens bibliotek, og bruger det til at vise på skærmen. Men hjemmesiden omdøber af gode grunde filer.zip til filer-1.zip, filer-2.zip, osv. Tilsvarende med poster.pdf. Har du mulighed for at ændre hvor hjemmesiden tager navnet fra? Lige nu skriver jeg "poster" og "filer" i filernes titel-felt når jeg uploader, så det ville være ideelt. Under beskrivelse vil jeg begynde at skrive en meget kort tekst som kæder filen sammen med det relevante forløb.

**Comment by Graunephar** [comment]
Fixed. Nu er det indholdet af "Titel" feltet som bruges som tekst. 

Går ud fra det var det du mente der skulle til.
